In [21]:
import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [22]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [4]:
#data Analysis

df.head(8)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN
5,843786,M,12.45,15.70,82.57,477.1,0.12780,0.17000,0.15780,0.08089,...,23.75,103.40,741.6,0.1791,0.5249,0.5355,0.1741,0.3985,0.12440,NaN
6,844359,M,18.25,19.98,119.60,1040.0,0.09463,0.10900,0.11270,0.07400,...,27.66,153.20,1606.0,0.1442,0.2576,0.3784,0.1932,0.3063,0.08368,NaN
7,84458202,M,13.71,20.83,90.20,577.9,0.11890,0.16450,0.09366,0.05985,...,28.14,110.60,897.0,0.1654,0.3682,0.2678,0.1556,0.3196,0.11510,NaN

In [5]:
# df.loc[:,['radius_mean','texture_mean']]
df.iloc[:,2:6]

     radius_mean  texture_mean  perimeter_mean  area_mean
0          17.99         10.38          122.80     1001.0
1          20.57         17.77          132.90     1326.0
2          19.69         21.25          130.00     1203.0
3          11.42         20.38           77.58      386.1
4          20.29         14.34          135.10     1297.0
..           ...           ...             ...        ...
564        21.56         22.39          142.00     1479.0
565        20.13         28.25          131.20     1261.0
566        16.60         28.08          108.30      858.1
567        20.60         29.33          140.10     1265.0
568         7.76         24.54           47.92      181.0

[569 rows x 4 columns]

In [22]:
df.loc[df['radius_mean']>20,'radius_mean']

1      20.57
4      20.29
23     21.16
78     20.18
82     25.22
95     20.26
108    22.27
122    24.25
164    23.27
180    27.22
181    21.09
202    23.29
210    20.58
212    28.11
233    20.51
236    23.21
237    20.48
250    20.94
260    20.31
265    20.73
272    21.75
302    20.09
321    20.16
323    20.34
339    23.51
352    25.73
365    20.44
366    20.20
368    21.71
369    22.01
372    21.37
373    20.64
393    21.61
432    20.18
449    21.10
461    27.42
499    20.59
503    23.09
521    24.63
533    20.47
535    20.55
563    20.92
564    21.56
565    20.13
567    20.60
Name: radius_mean, dtype: float64

In [6]:
# df.iloc[df.iloc[:,2]>20]
col = df.columns.get_loc("radius_mean")
df.iloc[df.iloc[:, col] > 20,col]

1      20.57
4      20.29
23     21.16
78     20.18
82     25.22
95     20.26
108    22.27
122    24.25
164    23.27
180    27.22
181    21.09
202    23.29
210    20.58
212    28.11
233    20.51
236    23.21
237    20.48
250    20.94
260    20.31
265    20.73
272    21.75
302    20.09
321    20.16
323    20.34
339    23.51
352    25.73
365    20.44
366    20.20
368    21.71
369    22.01
372    21.37
373    20.64
393    21.61
432    20.18
449    21.10
461    27.42
499    20.59
503    23.09
521    24.63
533    20.47
535    20.55
563    20.92
564    21.56
565    20.13
567    20.60
Name: radius_mean, dtype: float64

In [7]:
df[df['radius_mean']>20][["radius_mean","compactness_mean"]]

     radius_mean  compactness_mean
1          20.57           0.07864
4          20.29           0.13280
23         21.16           0.10220
78         20.18           0.34540
82         25.22           0.26650
95         20.26           0.13130
108        22.27           0.27680
122        24.25           0.28670
164        23.27           0.11450
180        27.22           0.19140
181        21.09           0.28320
202        23.29           0.20840
210        20.58           0.13480
212        28.11           0.15160
233        20.51           0.10740
236        23.21           0.16820
237        20.48           0.08348
250        20.94           0.16060
260        20.31           0.10880
265        20.73           0.11430
272        21.75           0.19610
302        20.09           0.18380
321        20.16           0.08564
323        20.34           0.18750
339        23.51           0.12830
352        25.73           0.23630
365        20.44           0.11310
366        20.20           0.16690
368        21.71           0.08562
369        22.01           0.19540
372        21.37           0.15150
373        20.64           0.10760
393        21.61           0.20870
432        20.18           0.14890
449        21.10           0.11750
461        27.42           0.19880
499        20.59           0.16440
503        23.09           0.12750
521        24.63           0.21060
533        20.47           0.13130
535        20.55           0.17390
563        20.92           0.22360
564        21.56           0.11590
565        20.13           0.10340
567        20.60           0.27700

In [8]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='str')

In [26]:
df.loc[(df['concavity_mean'] < 0.5) & (df['symmetry_mean'] < 0.5), ["smoothness_mean", "compactness_mean"]]

     smoothness_mean  compactness_mean
0            0.11840           0.27760
1            0.08474           0.07864
2            0.10960           0.15990
3            0.14250           0.28390
4            0.10030           0.13280
..               ...               ...
564          0.11100           0.11590
565          0.09780           0.10340
566          0.08455           0.10230
567          0.11780           0.27700
568          0.05263           0.04362

[569 rows x 2 columns]

In [27]:
df.loc[:,['diagnosis','radius_mean']]

    diagnosis  radius_mean
0           M        17.99
1           M        20.57
2           M        19.69
3           M        11.42
4           M        20.29
..        ...          ...
564         M        21.56
565         M        20.13
566         M        16.60
567         M        20.60
568         B         7.76

[569 rows x 2 columns]

In [28]:
#min,max...all
# df.describe()
df["texture_mean"].describe()

count    569.000000
mean      19.289649
std        4.301036
min        9.710000
25%       16.170000
50%       18.840000
75%       21.800000
max       39.280000
Name: texture_mean, dtype: float64

In [29]:
df["texture_mean"].mean()

np.float64(19.289648506151142)

In [9]:
df.head(5)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [23]:
#Data Prepocessing

#remove the null columns

df.drop(columns=["id","Unnamed: 32"],inplace=True)

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   diagnosis                569 non-null    str
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  569 non-null    float64
 15  smoothness_se            569 non-null    float64
 16  compactness_se           569 non-null    float64
 17  concavity_se             569 non-null    float64
 18  concave points_se        569 non-null    float64
 19  symmetry_se              569 non-null    float64
 20  fractal_dimension_se     569 non-null    float64
 21  radius_worst             569 non-null    float64
 22  texture_worst            569 non-null    float64
 23  perimeter_worst          569 non-null    float64
 24  area_worst               569 non-null    float64
 25  smoothness_worst         569 non-null    float64
 26  compactness_worst        569 non-null    float64
 27  concavity_worst          569 non-null    float64
 28  concave points_worst     569 non-null    float64
 29  symmetry_worst           569 non-null    float64
 30  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30), str(1)
memory usage: 137.9 KB

In [12]:
df.iloc[:,0]

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: str

In [24]:

features=df.iloc[:,1:]
target=df["diagnosis"]

In [5]:
features

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [6]:
target

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: str

In [25]:
#standard scaler

std_scaler=StandardScaler()

scaled_df=std_scaler.fit_transform(features)

In [ ]:
#lable encoder for target column
# lab=LabelEncoder()
# labeled_target=lab.fit_transform(target)

In [17]:
# labeled_target

In [26]:
#another way using the map
# map() returns a pandas Series.
# LabelEncoder.fit_transform() returns a NumPy ndarray.
labeled_target=target.map({"M":1,"B":0}).to_numpy()

In [9]:
labeled_target

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0])

In [27]:
#test_train_split data
xtrain,xtest,ytrain,ytest=train_test_split(scaled_df,labeled_target,test_size=0.2)
print(xtrain.shape)
print(xtest.shape)
print(ytest.shape)
print(ytrain.shape)

(455, 30)
(114, 30)
(114,)
(455,)

In [11]:
print(xtrain.dtype)
print(type(ytrain))

float64
<class 'numpy.ndarray'>

In [28]:
#Numpy arrays to pytorch tensors
xtrain_tensor=torch.from_numpy(xtrain.astype(np.float32))
xtest_tensor=torch.from_numpy(xtest.astype(np.float32))
ytrain_tensor = torch.from_numpy(ytrain.astype(np.float32)).view(-1,1)
ytest_tensor = torch.from_numpy(ytest.astype(np.float32)).view(-1,1)

In [24]:
print(xtrain_tensor.shape)
print(xtest_tensor.shape)
print(ytrain_tensor.shape)
print(ytest_tensor.shape)

torch.Size([455, 30])
torch.Size([114, 30])
torch.Size([455, 1])
torch.Size([114, 1])

In [29]:
#Defining the model

import torch
import torch.nn as nn

class MyModel(nn.Module):
    def __init__(self,features):
        super().__init__()
        self.linear1=nn.Linear(features,5)
        self.relu1=nn.ReLU()
        self.linear2=nn.Linear(5,3)
        self.relu2=nn.ReLU()
        self.linear3=nn.Linear(3,1)
        self.sigmoid1=nn.Sigmoid()
    
    def forward(self,features):
         out = self.linear1(features)
         out = self.relu1(out)
         out = self.linear2(out)
         out = self.relu2(out)
         out = self.linear3(out)
         out = self.sigmoid1(out)
         return out

In [30]:
#Training the Network
learning_rate=0.1

#define how many epocha
epochs=100

#define the loss function
loss_function=nn.BCELoss()

#create model
model=MyModel(xtrain_tensor.shape[1])
# print(model.shape)

# define optimizer
optimizer = torch.optim.Adam(model.parameters(),lr=learning_rate)

In [31]:
#defining the tensorboard
from torch.utils.tensorboard import SummaryWriter
writer=SummaryWriter(log_dir='runs/cancer')

In [32]:
for epoch in range(epochs):
    model.train()
    
    y_pred=model(xtrain_tensor)
    
    loss=loss_function(y_pred,ytrain_tensor)
   
    optimizer.zero_grad()
    
    loss.backward()
    
    optimizer.step()
   
   # train accuracy (no grad needed for the metric)
    with torch.no_grad():
    # (y_pred > 0.5) turns probabilities into 0/1 predictions, shape (455, 1).
    # We compare against y_train_2d which is also (455, 1) -> element-wise match.
       train_acc=((y_pred>0.5).float()==ytrain_tensor).float().mean()

# ---- validation (on the held-out test set) ----
    model.eval()  # put model in evaluation mode
    with torch.no_grad():
      val_pred = model(xtest_tensor)              # shape (114, 1)
      val_loss = loss_function(val_pred, ytest_tensor)
      val_acc = ((val_pred > 0.5).float() == ytest_tensor).float().mean()
      
    writer.add_scalar('Loss/train',loss.item(),epoch+1)
    writer.add_scalar('Loss/val',val_loss.item(),epoch+1)
    writer.add_scalar('Accuracy/train', train_acc.item(), epoch + 1)
    writer.add_scalar('Accuracy/val', val_acc.item(), epoch + 1)
    
  # print metrics in each epoch
    print(f'Epoch: {epoch + 1}, '
    f'Train Loss: {loss.item():.4f}, Val Loss: {val_loss.item():.4f}, '
    f'Train Acc: {train_acc.item():.4f}, Val Acc: {val_acc.item():.4f}')

writer.close()

Epoch: 1, Train Loss: 0.6697, Val Loss: 0.5095, Train Acc: 0.6308, Val Acc: 0.6140
Epoch: 2, Train Loss: 0.5048, Val Loss: 0.4272, Train Acc: 0.6308, Val Acc: 0.6140
Epoch: 3, Train Loss: 0.4058, Val Loss: 0.3937, Train Acc: 0.6308, Val Acc: 0.6140
Epoch: 4, Train Loss: 0.3575, Val Loss: 0.3765, Train Acc: 0.6308, Val Acc: 0.6140
Epoch: 5, Train Loss: 0.3323, Val Loss: 0.3548, Train Acc: 0.6308, Val Acc: 0.9298
Epoch: 6, Train Loss: 0.3081, Val Loss: 0.3321, Train Acc: 0.9495, Val Acc: 0.9474
Epoch: 7, Train Loss: 0.2851, Val Loss: 0.3130, Train Acc: 0.9626, Val Acc: 0.9474
Epoch: 8, Train Loss: 0.2645, Val Loss: 0.2953, Train Acc: 0.9692, Val Acc: 0.9561
Epoch: 9, Train Loss: 0.2458, Val Loss: 0.2815, Train Acc: 0.9824, Val Acc: 0.9561
Epoch: 10, Train Loss: 0.2312, Val Loss: 0.2692, Train Acc: 0.9846, Val Acc: 0.9561
Epoch: 11, Train Loss: 0.2183, Val Loss: 0.2624, Train Acc: 0.9802, Val Acc: 0.9561
Epoch: 12, Train Loss: 0.2078, Val Loss: 0.2570, Train Acc: 0.9780, Val Acc: 0.9649
Epoch: 13, Train Loss: 0.1977, Val Loss: 0.2525, Train Acc: 0.9780, Val Acc: 0.9561
Epoch: 14, Train Loss: 0.1857, Val Loss: 0.2505, Train Acc: 0.9780, Val Acc: 0.9561
Epoch: 15, Train Loss: 0.1753, Val Loss: 0.2503, Train Acc: 0.9780, Val Acc: 0.9561
Epoch: 16, Train Loss: 0.1662, Val Loss: 0.2461, Train Acc: 0.9802, Val Acc: 0.9474
Epoch: 17, Train Loss: 0.1576, Val Loss: 0.2378, Train Acc: 0.9824, Val Acc: 0.9561
Epoch: 18, Train Loss: 0.1485, Val Loss: 0.2255, Train Acc: 0.9824, Val Acc: 0.9561
Epoch: 19, Train Loss: 0.1388, Val Loss: 0.2130, Train Acc: 0.9846, Val Acc: 0.9561
Epoch: 20, Train Loss: 0.1304, Val Loss: 0.2013, Train Acc: 0.9868, Val Acc: 0.9561
Epoch: 21, Train Loss: 0.1223, Val Loss: 0.1896, Train Acc: 0.9868, Val Acc: 0.9649
Epoch: 22, Train Loss: 0.1130, Val Loss: 0.1849, Train Acc: 0.9868, Val Acc: 0.9649
Epoch: 23, Train Loss: 0.1051, Val Loss: 0.1870, Train Acc: 0.9912, Val Acc: 0.9649
Epoch: 24, Train Loss: 0.0998, Val Loss: 0.1929, Train Acc: 0.9912, Val Acc: 0.9649
Epoch: 25, Train Loss: 0.0955, Val Loss: 0.1985, Train Acc: 0.9868, Val Acc: 0.9649
Epoch: 26, Train Loss: 0.0898, Val Loss: 0.2015, Train Acc: 0.9890, Val Acc: 0.9649
Epoch: 27, Train Loss: 0.0835, Val Loss: 0.2012, Train Acc: 0.9912, Val Acc: 0.9649
Epoch: 28, Train Loss: 0.0773, Val Loss: 0.1997, Train Acc: 0.9912, Val Acc: 0.9649
Epoch: 29, Train Loss: 0.0724, Val Loss: 0.1971, Train Acc: 0.9912, Val Acc: 0.9649
Epoch: 30, Train Loss: 0.0679, Val Loss: 0.1953, Train Acc: 0.9934, Val Acc: 0.9561
Epoch: 31, Train Loss: 0.0637, Val Loss: 0.1955, Train Acc: 0.9934, Val Acc: 0.9561
Epoch: 32, Train Loss: 0.0593, Val Loss: 0.1997, Train Acc: 0.9956, Val Acc: 0.9561
Epoch: 33, Train Loss: 0.0548, Val Loss: 0.2098, Train Acc: 0.9956, Val Acc: 0.9561
Epoch: 34, Train Loss: 0.0505, Val Loss: 0.2268, Train Acc: 0.9956, Val Acc: 0.9561
Epoch: 35, Train Loss: 0.0466, Val Loss: 0.2492, Train Acc: 0.9956, Val Acc: 0.9561
Epoch: 36, Train Loss: 0.0430, Val Loss: 0.2738, Train Acc: 0.9978, Val Acc: 0.9561
Epoch: 37, Train Loss: 0.0403, Val Loss: 0.2971, Train Acc: 1.0000, Val Acc: 0.9561
Epoch: 38, Train Loss: 0.0376, Val Loss: 0.3179, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 39, Train Loss: 0.0352, Val Loss: 0.3404, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 40, Train Loss: 0.0332, Val Loss: 0.3677, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 41, Train Loss: 0.0312, Val Loss: 0.3918, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 42, Train Loss: 0.0295, Val Loss: 0.4089, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 43, Train Loss: 0.0278, Val Loss: 0.4151, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 44, Train Loss: 0.0264, Val Loss: 0.4065, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 45, Train Loss: 0.0251, Val Loss: 0.3937, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 46, Train Loss: 0.0240, Val Loss: 0.3787, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 47, Train Loss: 0.0230, Val Loss: 0.3652, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 48, Train Loss: 0.0221, Val Loss: 0.3555, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 49, Train Loss: 0.0211, Val Loss: 0.3503, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 50, Train Loss: 0.0201, Val Loss: 0.3471, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 51, Train Loss: 0.0193, Val Loss: 0.3447, Train Acc: 1.0000, Val Acc: 0.9737
Epoch: 52, Train Loss: 0.0187, Val Loss: 0.3405, Train Acc: 1.0000, Val Acc: 0.9737
Epoch: 53, Train Loss: 0.0180, Val Loss: 0.3344, Train Acc: 1.0000, Val Acc: 0.9737
Epoch: 54, Train Loss: 0.0173, Val Loss: 0.3279, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 55, Train Loss: 0.0166, Val Loss: 0.3221, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 56, Train Loss: 0.0161, Val Loss: 0.3185, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 57, Train Loss: 0.0157, Val Loss: 0.3196, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 58, Train Loss: 0.0153, Val Loss: 0.3249, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 59, Train Loss: 0.0147, Val Loss: 0.3309, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 60, Train Loss: 0.0142, Val Loss: 0.3379, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 61, Train Loss: 0.0139, Val Loss: 0.3405, Train Acc: 1.0000, Val Acc: 0.9737
Epoch: 62, Train Loss: 0.0135, Val Loss: 0.3382, Train Acc: 1.0000, Val Acc: 0.9737
Epoch: 63, Train Loss: 0.0132, Val Loss: 0.3355, Train Acc: 1.0000, Val Acc: 0.9737
Epoch: 64, Train Loss: 0.0128, Val Loss: 0.3320, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 65, Train Loss: 0.0125, Val Loss: 0.3283, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 66, Train Loss: 0.0122, Val Loss: 0.3255, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 67, Train Loss: 0.0119, Val Loss: 0.3253, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 68, Train Loss: 0.0116, Val Loss: 0.3288, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 69, Train Loss: 0.0113, Val Loss: 0.3339, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 70, Train Loss: 0.0111, Val Loss: 0.3400, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 71, Train Loss: 0.0108, Val Loss: 0.3471, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 72, Train Loss: 0.0106, Val Loss: 0.3543, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 73, Train Loss: 0.0104, Val Loss: 0.3616, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 74, Train Loss: 0.0102, Val Loss: 0.3687, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 75, Train Loss: 0.0100, Val Loss: 0.3754, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 76, Train Loss: 0.0098, Val Loss: 0.3808, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 77, Train Loss: 0.0096, Val Loss: 0.3859, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 78, Train Loss: 0.0094, Val Loss: 0.3908, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 79, Train Loss: 0.0093, Val Loss: 0.3957, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 80, Train Loss: 0.0091, Val Loss: 0.4002, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 81, Train Loss: 0.0090, Val Loss: 0.4044, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 82, Train Loss: 0.0088, Val Loss: 0.4084, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 83, Train Loss: 0.0087, Val Loss: 0.4119, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 84, Train Loss: 0.0085, Val Loss: 0.4153, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 85, Train Loss: 0.0084, Val Loss: 0.4189, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 86, Train Loss: 0.0082, Val Loss: 0.4227, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 87, Train Loss: 0.0081, Val Loss: 0.4266, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 88, Train Loss: 0.0080, Val Loss: 0.4306, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 89, Train Loss: 0.0079, Val Loss: 0.4348, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 90, Train Loss: 0.0078, Val Loss: 0.4392, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 91, Train Loss: 0.0076, Val Loss: 0.4435, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 92, Train Loss: 0.0075, Val Loss: 0.4478, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 93, Train Loss: 0.0074, Val Loss: 0.4518, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 94, Train Loss: 0.0073, Val Loss: 0.4555, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 95, Train Loss: 0.0072, Val Loss: 0.4589, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 96, Train Loss: 0.0071, Val Loss: 0.4621, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 97, Train Loss: 0.0070, Val Loss: 0.4650, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 98, Train Loss: 0.0069, Val Loss: 0.4677, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 99, Train Loss: 0.0068, Val Loss: 0.4705, Train Acc: 1.0000, Val Acc: 0.9649
Epoch: 100, Train Loss: 0.0067, Val Loss: 0.4735, Train Acc: 1.0000, Val Acc: 0.9649

In [33]:
!tensorboard --logdir=runs/cancer --port=6007

TensorFlow installation not found - running with reduced feature set.
E0723 19:42:20.054648 16104 program.py:300] TensorBoard could not bind to port 6007, it was already in use
ERROR: TensorBoard could not bind to port 6007, it was already in use

In [34]:
%load_ext tensorboard
%tensorboard --logdir runs